### PR TITLE
Promise

### PR DESCRIPTION
**Pull request by luizmb**

### CODE REVIEW

**Comment by zweigraf** [comment]
Quick Question: If I pass around a promise, and multiple people subscribe, will this trigger multiple source actions?

Can I pass around a completed promise and it will always be completed? Or can I only pass around "cold" promises?

**Comment by luizmb** [comment]
That's a good question, the way I implemented follows most Publishers in Combine, that behave like value types, you pass a copy and then it will be executed multiple times. To avoid that you need to call ".share" in a Publisher, which returns a class Publisher (in opposite to most other publishers that are struct) and this will trigger the side-effect immediately (not upon subscription), so it's eager (unfortunately). More than that, IIRC ".share" will force a .unlimited backpressure to upstream, which is weird if you ask me, but I guess it would be hard to control the demand of all downstreams and make a "demand race" between them.

Anyway. if you want, you can "share" the promise and that will trigger the side-effect immediately, but cache the result and notify every new subscriber (actually I'm not totally sure about share+replay or only share, but if the share doesn't buffer the past results, I'm pretty sure CombineExt is implementing that because RxSwift has similar Share+ReplayLast and Share+ReplayMany.

**Comment by zweigraf** [comment]
Interesting. I am just talking out of javascript experience, in which promises are always hot, and always shared. 

Have never worked with Promises outside of JS, so I don't know if JS is the anomaly or this.

**Comment by luizmb** [comment]
Yes, Future on Combine also works like that, it's eager, starts not depending on backpressure or subscription, and shares the results keeping them in cache.
Unfortunately Apple docs are missing all details :(
https://developer.apple.com/documentation/combine/future

**Pull request merged**
