### PR TITLE
Added range value calculations Helper

### PR DESCRIPTION
**Pull request by GiuliaAriu**

### CODE REVIEW

**Comment by LukasLiebl** [comment]
Would be nice if you could add some tests with symmetric as well as asymmetric ranges

**Comment by OguzYuuksel** [comment]
Instead of creating a placeholder struct, it would be more Swift way to extend `Numeric` protocol for `calculatePercentageFromValueInRange`, and `BinaryFloatingPoint` protocol for `calculateValueInRangeFromPercentage`, also it would make sense to ask AI for the proper method and argument names for extensions.

**Comment by LukasLiebl** [comment]
> Instead of creating a placeholder struct, it would be more Swift way to extend `Numeric` protocol for `calculatePercentageFromValueInRange`, and `BinaryFloatingPoint` protocol for `calculateValueInRangeFromPercentage`, also it would make sense to ask AI for the proper method and argument names for extensions.

As an extension on ClosedRange or Numeric it'd be fine for me. I'd also not have anything against this implementation as it is kind of specific

**Comment by luizmb** [comment]
https://github.com/teufelaudio/FoundationExtensions/blob/master/Sources/FoundationExtensions/Numeric/Numeric%2BExtensions.swift#L39C3-L39C14

**Review by LukasLiebl — APPROVED** [review]

**Pull request merged**
